FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/
COPY leanai/modeling/train.py /app/leanai/modeling/train.py
COPY models /app/models

RUN pip install --upgrade pip && pip install -r /app/requirements.txt

CMD ["python", "leanai/modeling/train.py"]
