# use Python 3.9
FROM python:3.9-slim

# Install working directory
WORKDIR /app

# Copy project files
COPY api /app/api
COPY models /app/models
COPY requirements.txt /app/

# Install requirements
RUN pip install --upgrade pip \
    && if [ -f "/app/requirements.txt" ]; then pip install -r /app/requirements.txt; fi

# Open port 8000
EXPOSE 8000

# Run FastAPI server
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
